// Identifies AI-generated content wherever an estimate is shown (spec §8, transparency).
export const AiDisclosure = () => (
  <p className="flex items-center gap-2 text-xs text-muted-foreground">
    <span aria-hidden className="rounded-sm border border-border-strong px-1 font-medium text-foreground">
      AI
    </span>
    Generated by AI from your transcript. Review before sharing with a client.
  </p>
);
