import { act, cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { fullEstimate, fullResponse } from "@/lib/estimate/fixtures";
import type { StreamState } from "@/lib/estimate/types";
import { AssistantMessage } from "./assistant-message";

const DISCLOSURE = "Generated by AI from your transcript. Review before sharing with a client.";
const partial = { project_name: "Physiotherapy portal", summary: "Patients book sessions." };

const streaming: StreamState = { status: "streaming", phase: "calling_llm", partial, startedAt: 0 };
const done: StreamState = { status: "done", result: fullResponse, requestId: "req-42" };
const cancelled: StreamState = { status: "cancelled", partial };
const failed = (code: string, extra: { retryable?: boolean; requestId?: string; details?: { type: string }[] } = {}): StreamState => ({
  status: "error",
  error: { code, message: "upstream detail", retryable: extra.retryable ?? false, requestId: extra.requestId, details: extra.details },
  partial,
});

// The latest turn of a conversation: `onRetry` is given (S5-R3: only a stopped or failed turn uses it).
const setup = (state: StreamState) => {
  const handlers = { onStop: vi.fn(), onRetry: vi.fn(), onEditTranscript: vi.fn() };
  const user = userEvent.setup();
  const view = render(<AssistantMessage state={state} {...handlers} />);
  const rerender = (next: StreamState) => view.rerender(<AssistantMessage state={next} {...handlers} />);
  return { ...handlers, user, rerender };
};
const button = (name: string | RegExp) => screen.getByRole("button", { name });
const noButton = (name: string | RegExp) => expect(screen.queryByRole("button", { name })).not.toBeInTheDocument();

describe("AssistantMessage while streaming", () => {
  it("shows the status steps, the estimate so far and a Stop button", async () => {
    const { user, onStop } = setup(streaming);
    expect(screen.getByRole("list", { name: "Progress" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { level: 2, name: "Physiotherapy portal" })).toBeInTheDocument();
    expect(screen.getByRole("article")).toHaveAttribute("aria-busy", "true");
    expect(screen.getByText(DISCLOSURE)).toBeInTheDocument();
    noButton("Retry");
    noButton("Copy as markdown");

    await user.click(button("Stop"));
    expect(onStop).toHaveBeenCalledTimes(1);
  });

  it("shows skeletons shaped like the estimate before the first snapshot", () => {
    setup({ ...streaming, partial: null });
    expect(screen.getByRole("article").querySelectorAll('[data-slot="skeleton"]').length).toBeGreaterThan(0);
  });

  it("stops on Escape, but not when another layer already handled it", async () => {
    const { user, onStop } = setup(streaming);
    await user.keyboard("{Escape}");
    expect(onStop).toHaveBeenCalledTimes(1);

    const handled = (event: KeyboardEvent) => event.preventDefault();
    document.addEventListener("keydown", handled, { capture: true });
    await user.keyboard("{Escape}");
    document.removeEventListener("keydown", handled, { capture: true });
    expect(onStop).toHaveBeenCalledTimes(1);
  });

  it("ignores Escape while an IME composition is active", () => {
    const { onStop } = setup(streaming);
    fireEvent.keyDown(document.body, { key: "Escape", isComposing: true });
    fireEvent.keyDown(document.body, { key: "Escape", keyCode: 229 }); // Safari ends the composition before this keydown
    expect(onStop).not.toHaveBeenCalled();
    fireEvent.keyDown(document.body, { key: "Escape" });
    expect(onStop).toHaveBeenCalledTimes(1);
  });

  it("ignores Escape once the stream has ended", async () => {
    const { user, onStop, rerender } = setup(streaming);
    rerender(done);
    await user.keyboard("{Escape}");
    expect(onStop).not.toHaveBeenCalled();
  });
});

describe("AssistantMessage when done", () => {
  // S5-R3: running a completed turn again would fork the conversation's history.
  it("renders the final estimate with the AI disclosure and Copy as markdown, and no way to run it again", async () => {
    const { user } = setup(done);
    expect(screen.getByRole("heading", { level: 2, name: fullEstimate.project_name })).toBeInTheDocument();
    expect(screen.getByRole("article")).toHaveAttribute("aria-busy", "false");
    expect(screen.getByText(DISCLOSURE)).toBeInTheDocument();
    noButton("Stop");
    noButton("Retry");
    noButton("Regenerate");

    await user.click(button("Copy as markdown"));
    expect(await navigator.clipboard.readText()).toBe(fullResponse.estimation);
  });

  it("copies the open questions for the client as a plain numbered list", async () => {
    const { user } = setup(done);
    await user.click(button("Copy questions for the client"));
    expect(await navigator.clipboard.readText()).toBe(
      "1. Does the ClinicCloud API allow creating and cancelling bookings?\n2. Who uploads the exercise videos, and how large are they?",
    );
  });

  it("offers no question copy when the estimate has no open questions", () => {
    setup({ ...done, result: { ...fullResponse, breakdown: { ...fullEstimate, open_questions: [] } } });
    noButton("Copy questions for the client");
    expect(button("Copy as markdown")).toBeInTheDocument();
  });
});

describe("AssistantMessage on error", () => {
  it("shows the mapped message with Try again, keeping the partial content", async () => {
    const { user, onRetry } = setup(failed("upstream_unavailable", { retryable: true }));
    const card = screen.getByRole("alert");
    expect(card).toHaveTextContent("The AI service is unavailable right now. Try again in a moment.");
    expect(screen.getByRole("heading", { level: 2, name: "Physiotherapy portal" })).toBeInTheDocument();
    expect(screen.getByText("Patients book sessions.")).toBeInTheDocument();
    noButton("Stop");

    await user.click(within(card).getByRole("button", { name: "Try again" }));
    expect(onRetry).toHaveBeenCalledTimes(1);
  });

  it("asks to shorten an over-long transcript and puts it back in the form", async () => {
    const { user, onEditTranscript } = setup(failed("invalid_request", { details: [{ type: "string_too_long" }] }));
    expect(screen.getByRole("alert")).toHaveTextContent("The transcript is over the character limit. Shorten it and try again.");
    await user.click(button("Edit transcript"));
    expect(onEditTranscript).toHaveBeenCalledTimes(1);
  });

  it("lets the user copy the request ID when support is the way forward", async () => {
    const { user } = setup(failed("internal_error", { requestId: "req-500" }));
    const card = screen.getByRole("alert");
    expect(card).toHaveTextContent("Share the request ID with support.");
    expect(card).toHaveTextContent("req-500");
    await user.click(within(card).getByRole("button", { name: "Copy request ID" }));
    expect(await navigator.clipboard.readText()).toBe("req-500");
  });

  it("renders no estimate when the stream failed before the first snapshot", () => {
    setup({ status: "error", error: { code: "upstream_unavailable", message: "down", retryable: true }, partial: null });
    expect(screen.queryByRole("article")).not.toBeInTheDocument();
    expect(screen.queryByText(DISCLOSURE)).not.toBeInTheDocument();
  });
});

describe("AssistantMessage when stopped", () => {
  it("says Stopped in a live region that was already there, keeps the partial content and offers Retry", async () => {
    const { user, onRetry, rerender } = setup(streaming);
    const regions = screen.getAllByRole("status");
    rerender(cancelled);
    expect(regions).toContain(screen.getByText("Stopped").closest('[role="status"]')); // so the change is announced
    expect(screen.getByRole("heading", { level: 2, name: "Physiotherapy portal" })).toBeInTheDocument();
    expect(screen.getByRole("article")).toHaveAttribute("aria-busy", "false");
    noButton("Copy as markdown");

    await user.click(button("Retry"));
    expect(onRetry).toHaveBeenCalledTimes(1);
  });
});

// One polite region announces completion: a stream that stops or fails never claims it is ready.
describe("AssistantMessage completion announcement", () => {
  it.each([
    ["stopped", cancelled],
    ["failed", failed("upstream_unavailable", { retryable: true })],
  ])("never announces 'Estimate ready' when the stream %s", (_, end) => {
    const { rerender } = setup(streaming);
    const ready = within(screen.getByRole("article")).getByRole("status");
    expect(ready).toBeEmptyDOMElement();
    rerender(end);
    expect(within(screen.getByRole("article")).getByRole("status")).toBe(ready); // same region, so a change would be announced
    expect(ready).toBeEmptyDOMElement();
  });

  it("announces 'Estimate ready' in the same region when the stream completes", () => {
    const { rerender } = setup(streaming);
    const ready = within(screen.getByRole("article")).getByRole("status");
    rerender(done);
    expect(within(screen.getByRole("article")).getByRole("status")).toBe(ready);
    expect(ready).toHaveTextContent("Estimate ready");
  });
});

describe("AssistantMessage focus management", () => {
  it("moves focus to Retry after Stop, and to Stop after Retry, without scrolling", async () => {
    const { user, rerender } = setup(streaming);
    const focus = vi.spyOn(HTMLElement.prototype, "focus");
    await user.click(button("Stop"));
    rerender(cancelled);
    expect(button("Retry")).toHaveFocus();
    expect(focus).toHaveBeenLastCalledWith({ preventScroll: true });
    focus.mockRestore();

    await user.click(button("Retry"));
    rerender(streaming);
    expect(button("Stop")).toHaveFocus();
  });

  it("moves focus to the first action when the stream ends under a focused Stop", () => {
    const { rerender } = setup(streaming);
    button("Stop").focus();
    rerender(done);
    expect(button("Copy as markdown")).toHaveFocus();
  });

  it("moves focus to the error card's action when the stream fails under a focused Stop", () => {
    const { rerender } = setup(streaming);
    button("Stop").focus();
    rerender(failed("upstream_unavailable", { retryable: true }));
    expect(button("Try again")).toHaveFocus();
  });

  it("refocuses after its own Stop even when the click did not focus the button (Safari)", () => {
    const { rerender } = setup(streaming);
    fireEvent.click(button("Stop")); // no focus change, as Safari does for buttons
    expect(document.body).toHaveFocus();
    rerender(cancelled);
    expect(button("Retry")).toHaveFocus();
  });

  it("never takes focus that was last in another message", () => {
    const handlers = { onStop: vi.fn(), onRetry: vi.fn(), onEditTranscript: vi.fn() };
    const Two = ({ second }: { second: StreamState }) => (
      <>
        <AssistantMessage state={done} {...handlers} />
        <AssistantMessage state={second} {...handlers} />
      </>
    );
    const view = render(<Two second={streaming} />);
    const [firstCopy] = screen.getAllByRole("button", { name: "Copy as markdown" });
    act(() => firstCopy.focus());
    act(() => firstCopy.blur()); // e.g. a click on blank space: focus falls to the page
    view.rerender(<Two second={done} />);
    expect(document.body).toHaveFocus();
  });

  it("leaves focus alone when it is elsewhere, and never takes it on mount", () => {
    const outside = document.body.appendChild(document.createElement("textarea"));
    outside.focus();
    const { rerender } = setup(streaming);
    rerender(cancelled);
    expect(outside).toHaveFocus();
    outside.remove();

    setup(done);
    expect(document.body).toHaveFocus();
  });
});

// A conversation turn (S5-R3): running a completed turn again would fork the history, so only a stopped or failed one
// can be retried, and only while it is the latest turn (the workspace passes `onRetry` then).
describe("AssistantMessage as a conversation turn", () => {
  // An earlier turn: a later one exists, so the workspace passes no `onRetry`.
  const earlier = (state: StreamState) => render(<AssistantMessage state={state} onStop={vi.fn()} onEditTranscript={vi.fn()} />);

  it("offers no way to run an earlier stopped or failed turn again", () => {
    earlier(cancelled);
    noButton("Retry");
    cleanup();
    earlier(failed("upstream_unavailable", { retryable: true }));
    expect(screen.getByRole("alert")).toHaveTextContent("The AI service is unavailable right now.");
    noButton("Try again");
  });

  it("puts a turn whose attachment was rejected back in the composer", async () => {
    const { user, onEditTranscript } = setup({
      status: "error",
      error: { code: "invalid_attachment", message: "virus.exe: unsupported file type (PDF, DOCX or plain text only)", retryable: false },
      partial: null,
    });
    expect(screen.getByRole("alert")).toHaveTextContent("An attachment was rejected: virus.exe: unsupported file type (PDF, DOCX or plain text only).");
    await user.click(button("Edit attachments"));
    expect(onEditTranscript).toHaveBeenCalledTimes(1);
    noButton("Try again"); // the same files would be rejected again
  });

  it("captions a grounded quote that is not in this turn's transcript with where it came from", async () => {
    render(<AssistantMessage state={done} onStop={vi.fn()} onEditTranscript={vi.fn()} evidenceNote={(id) => (id === "R2" ? "Quote from an earlier message" : undefined)} />);
    act(() => button("Evidence for R2").focus());
    expect(await screen.findByText("Quote from an earlier message")).toBeInTheDocument();
    act(() => button("Evidence for R1").focus());
    expect(await screen.findByText("Quote from the transcript")).toBeInTheDocument();
  });
});
